/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class splittablecodec_NativeCodecDecompressor */
#include "Dsrc.h"

#ifndef _Included_splittablecodec_NativeCodecDecompressor
#define _Included_splittablecodec_NativeCodecDecompressor
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_splittablecodec_NativeCodecDecompressor_initIDs
	(JNIEnv *, jclass);

JNIEXPORT int JNICALL Java_splittablecodec_NativeCodecDecompressor_decompress
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_splittablecodec_NativeCodecDecompressor_setParameters
  (JNIEnv *, jclass, jbyteArray parameters_array);

#ifdef __cplusplus
}
#endif
#endif
